baseURL = 'https://ogregoire.github.io/pf2-tools/'
languageCode = 'en-us'
title = 'PF2 Tools'
theme = 'hugo-book'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'PF2 Tools'
    contentDir = 'content/en'

  [languages.fr]
    languageName = 'Français'
    weight = 2
    title = 'Outils PF2'
    contentDir = 'content/fr'

[params]
  description = 'Pathfinder 2e Remastered Tools'
  BookRepo = 'https://github.com/ogregoire/pf2-tools'
  BookSection = '/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true